# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

app_title: Machon Shilo CMS

logo:
  src: /favicon.svg

backend:
  name: gitea
  repo: joshh613/www-machonshilo
  base_url: https://codeberg.org
  api_root: https://codeberg.org/api/v1

i18n:
  locales: [en, he]
  structure: multiple_folders

# field_defaults:

collections:
  - name: blog
    label: Blog
    # label_singular:
    # description:
    folder: src/content/blog
    slug: "{{fields._slug}}"
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: richtext }

# singletons:

editor:
  preview: false

media_folder: /src/assets/cms
public_folder: /src/assets/cms

media_libraries:
  default:
    config:
      slugify_filename: true
      transformations:
        raster_image:
          format: webp
          quality: 100
