# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

app_title: Machon Shilo CMS

logo:
  src: /favicon.svg

backend:
  name: gitea
  repo: joshh613/www-machonshilo
  base_url: https://codeberg.org
  api_root: https://codeberg.org/api/v1

i18n:
  locales: [en, he]
  structure: multiple_folders

# field_defaults:

collections:
  - name: pages
    label: Pages
    label_singular: Page
    # description:
    folder: src/content/pages
    slug: "{{fields._slug}}"
    i18n: true
    fields:
      - { name: title, label: Title, i18n: duplicate }
      - { name: body, label: Body, widget: richtext, i18n: duplicate }
  - name: responsa
    label: Responsa
    label_singular: Responsum
    # description:
    folder: src/content/responsa
    slug: "{{fields._slug}}"
    i18n: true
    fields:
      - { name: title, label: Title, i18n: duplicate }
      - { name: date_created, label: Date (created), widget: datetime, type: date, i18n: duplicate, required: false}
      - { name: body, label: Body, widget: richtext, i18n: duplicate }
  - name: articles
    label: Articles
    label_singular: Article
    # description:
    folder: src/content/articles
    slug: "{{fields._slug}}"
    i18n: true
    fields:
      - { name: title, label: Title, i18n: duplicate }
      - { name: date_created, label: Date (created), widget: datetime, type: date, i18n: duplicate, required: false}
      - { name: author, label: Author, widget: relation, collection: authors, default: rabbi-david-bar-hayim }
      - { name: body, label: Body, widget: richtext, i18n: duplicate }
  - name: authors
    label: Authors
    label_singular: Author
    folder: src/content/authors
    i18n: true
    identifier_field: name
    fields:
      - { name: name, label: Name, i18n: duplicate }
  - name: blog
    label: Blog
    folder: src/content/blog
    slug: "{{fields._slug}}"
    i18n: true
    fields:
      - { name: title, label: Title, i18n: duplicate }
      - { name: date_created, label: Date (created), widget: datetime, type: date, i18n: duplicate, required: false}
      - { name: body, label: Body, widget: richtext, i18n: duplicate }

# singletons:

editor:
  preview: false

media_folder: /src/assets/cms
public_folder: /src/assets/cms

media_libraries:
  default:
    config:
      slugify_filename: true
      transformations:
        raster_image:
          format: webp
          quality: 100
